server:
  port: 8090

spring:
  application:
    name: wire-mock
  devtools:
    restart:
      enabled: true

  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/wire-mock-db?createDatabaseIfNotExist=true
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  main:
    allow-bean-definition-overriding: true
  jackson:
    deserialization:
      fail-on-unknown-properties: true

third-party:
  base-url: http://localhost:8585
  version: v1
  trace-holder: 5000.00